### ISSUE TITLE
Hacer el radio de las ruedas configurable

### ISSUE THREAD

**Issue by franciscod** [memecimeters/memecimetro#22]
Actualmente el radio esta definido como 13.5.
[link al momento de escribir este issue](https://github.com/franciscod/memecimetro/commit/d2069462a2b5737527e2f700e13bb981822049d2#diff-8eb0e126eb9a562914678d2f121a9499L16)

- [x] revisar la unidad del radio (pulgadas? cm?) y documentarlo
- [x] hacer esto configurable (tal vez como un define en algun config.h o algo asi?)
- [ ] pensar si vale la pena hacer esto ajustable en runtime (cambiar el memecimetro de bici)

**Comment by FacundoMainere** [comment]
Me parece que considerando que es algo que no vas a modificar casi nunca no tiene sentido que sea en runtime

**Comment by baldosa** [comment]
está en pulgadas hoy en el código, yo creo que estaría bien medirlo en cm que es más amigable que pulgadas. Lo que no estoy seguro de que es exactamente ese radio, si al sensor o de la rueda entera. 
lo de configurable habría que hacerlo, ya que tenés varios tamaños de rueda (https://es.wikipedia.org/wiki/Rueda_de_bicicleta?oldformat=true). Podemos meter todo lo que sea config ahí onda brillo del lcd, layout1 o layout2, radio de rueda, etc.

123 a lo ke dise maine

**Comment by smarbos** [comment]
Si, en un archivo de configuracion. SLEEP_THERESHOLD_SECS también necesita ser definido en algún lado.

**Comment by franciscod** [comment]
constants.h config.h memes.h le_wild_variables.h

pick one

**Comment by baldosa** [comment]
le wild vars

**Comment by smarbos** [comment]
This config file is already implemented here #21

**Comment by baldosa** [comment]
lo volví a abrir porque esþa implementado el config file no la config en si

**Comment by smarbos** [comment]
Donde hace la matematica esa?

**Comment by baldosa** [comment]
https://github.com/franciscod/memecimetro/blob/master/code/src/main.cpp#L17

**Comment by baldosa** [comment]
https://github.com/franciscod/memecimetro/blob/master/code/src/main.cpp#L73

**Comment by baldosa** [comment]
#26
