### ISSUE TITLE
avg speed

### ISSUE THREAD

**Issue by baldosa** [memecimeters/memecimetro#23]
how to du dis

no podemos escribir topdo el tiempo o si?

**Comment by franciscod** [comment]
se pueden tener en RAM las "N velocidades instantaneas" que se miden, tomar el promedio y mostrar eso.. porque capaz si mandamos lo medido en crudo va a saltar demasiado. Despues se puede grabar a EEPROM periodicamente ese promedio (aca habria que investigar como hacer para que se "gaste" parejo, seguro alguna library de logging ya lo resuelve)

**Comment by FacundoMainere** [comment]
fixed in 64d7da2c25150bac1d87df
