### ISSUE TITLE
cadencia

### ISSUE THREAD

**Issue by baldosa** [memecimeters/memecimetro#24]
In cycling, cadence (or pedalling rate) is the number of revolutions of the crank per minute; this is the rate at which a cyclist is pedalling/turning the pedals. Cadence is directly proportional to wheel speed, but is a distinct measurement and changes with gearing—which determines the ratio of crank rpm to wheel rpm.

entiendo que podríamos saber la cadencia conociendo la relacion plato-piñon y la distancia por minuto si no tenés cambios o estoy flasheando cualkiera ?

**Comment by franciscod** [comment]
claro, si la relacion se mantiene fija es hacer una multiplicacion y listo.

yo pense que tenian bicis con cambios y eso donde la relacion te va cambiando entonces ahi tiene sentido tener dos sensores

**Comment by baldosa** [comment]
#26
