### ISSUE TITLE
grabar y apagar cuando tiene X min de inactivadad

### ISSUE THREAD

**Issue by baldosa** [memecimeters/memecimetro#3]
dis

**Comment by baldosa** [comment]
o dormir y no apagar

**Comment by smarbos** [comment]
cuanto tiempo de inactividad?

**Comment by franciscod** [comment]
Depende de cuan importante sea llevar la cuenta del tiempo con la bici
quieta.

Si no es importante, apenas pasan 2 segundos sin registrar una vuelta ya se
puede mandar a sleep

**Comment by smarbos** [comment]
Estaba pensando en hacer algo asi:

Definir una variable global timeSinceLastAction.

Cada vez que se sensa, actualizamos timeSinceLastAction con el numero de segundos desde que se inicio el memeduino:

`timeSinceLastAction = millis()/1000`

Y en cada vuelta, chequeo si timeSinceLastAction > umbral_de_apagado, si es así, pongo el memeduino a dormir para ahorrar batería.

Tal vez sea buena idea no hacerlo cada vuelta, sino cada 10 segundos, chequear timeSinceLastAction > umbral_de_apagado o algo asi.

Alguien tiene alguna mejor idea? No se cual es la forma ideal de hacer esto. discuss

**Comment by franciscod** [comment]
es buena esa. yo habia empezado a escribir algo parecido a esa idea pero lo perdi jajaja

**Comment by smarbos** [comment]
> Sleep is commonly used to save power on Arduino boards. For some Arduino variants, however, there is not much benefit. For example, the Arduino serial and USB boards use a 7805 type of power regulator, which needs 10mA when the Atmega IC is in idle mode. Putting these boards to sleep will cut a few mA off the total power consumption however it will still be high.
**# If you bypass the inefficient regulator with your own power supply circuit, or use a board with a fairly efficient power supply, such as an Arduino Pro, then sleep can be very beneficial for reducing power and extending battery life**. The regulator can even be removed altogether when using some Li-ion batteries.


When using SLEEP_MODE_IDLE, care must be taken to ensure that the 8-bit timer is disabled if you're using the arduino layer. The timer can be disabled before entering sleep using the PRR = PRR | 0b00100000; statement and subsequently re-enabled once out of sleep using PRR = PRR & 0b00000000; . The PRR refers to the Power Reduction Register. One must note that if this timer is disabled, the millis(); cannot be relied upon anymore if you need reliable data comparison before and after a sleep command.

     * The 5 different modes are:
     *     SLEEP_MODE_IDLE         -the least power savings
     *     SLEEP_MODE_ADC
     *     SLEEP_MODE_PWR_SAVE
     *     SLEEP_MODE_STANDBY
     *     SLEEP_MODE_PWR_DOWN     -the most power savings

http://playground.arduino.cc/Learning/ArduinoSleepCode

**Comment by smarbos** [comment]
http://www.nongnu.org/avr-libc/user-manual/group__avr__sleep.html

**Comment by franciscod** [comment]
http://www.gammon.com.au/power
